apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: bigdata-stack
type: Opaque
stringData:
  POSTGRES_USER: "hive"
  POSTGRES_PASSWORD: "hive"
  POSTGRES_DB: "metastore"


